server:
  port: 8501

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.67.168:23306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: db_user
    password: 9WLbHr%UYg
  data:
    redis:
      host: 117.72.67.168
      port: 16379
      password: 8Ahq$LOYUR1
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml
spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      - /webjars/**
      - /**/api-docs/**
      - /doc.html/**
  minio:
    endpointUrl: http://117.72.67.168:19000
    accessKey: minio
    secretKey: vZCNmwTbyOB
    bucketName: exercise-spzx-bucket
  captchaOnOff: false